baseURL = "https://fishingforkingfishers.com"
languageCode = "en-uk"
title = "Fishing for Kingfishers"
theme = "ananke"
resourceDir = "./resources"
Paginate = 10

[params]
  description = "(Mostly) bird photography (mostly) in the Midlands."
  background_color_class = "bg-black"
  logo="./static/great_tit_action_shot.jpg"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"